service: galeria

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-central-1
  environment:
      DEST_BUCKET: actiprofs/uploads
  role: arn:aws:iam::170048452532:role/serverless

functions:
  uploadAvatarImage:
    handler: ./handler.uploadAvatarImage
    events:
      - http:
          path: avatar/original
          method: post
          authorizer: arn:aws:lambda:eu-central-1:170048452532:function:auth-prod-authorizerFunc